apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ord-node1-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hlf-ordnode
      release: ord-node1
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: operations
      interval: 10s
      scrapeTimeout: 10s
      scheme: http