apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: org1-ca-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hlf-ca
      release: org1-ca
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: operations
      interval: 10s
      scrapeTimeout: 10s
      scheme: http