apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: org4-peer0-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hlf-peer
      release: org4-peer0
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: operations
      interval: 10s
      scrapeTimeout: 10s
      scheme: http