---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/status
  - replicasets
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - configmaps
  - deployments
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/status
  - replicasets
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console
  - fabriccas
  - fabricchaincodeapproves
  - fabricchaincodecommits
  - fabricchaincodeinstalls
  - fabricchaincodes
  - fabricchaincodetemplates
  - fabricfollowerchannels
  - fabricidentities
  - fabricmainchannels
  - fabricnetworkconfigs
  - fabricoperationsconsoles
  - fabricoperatorapis
  - fabricoperatoruis
  - fabricorderernodes
  - fabricorderingservices
  - fabricpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console/finalizers
  - console/status
  - fabriccas/finalizers
  - fabriccas/status
  - fabricchaincodeapproves/finalizers
  - fabricchaincodeapproves/status
  - fabricchaincodecommits/finalizers
  - fabricchaincodecommits/status
  - fabricchaincodeinstalls/finalizers
  - fabricchaincodeinstalls/status
  - fabricchaincodes/finalizers
  - fabricchaincodes/status
  - fabricchaincodetemplates/finalizers
  - fabricchaincodetemplates/status
  - fabricfollowerchannels/finalizers
  - fabricfollowerchannels/status
  - fabricidentities/finalizers
  - fabricidentities/status
  - fabricmainchannels/finalizers
  - fabricmainchannels/status
  - fabricnetworkconfigs/finalizers
  - fabricnetworkconfigs/status
  - fabricoperationsconsoles/finalizers
  - fabricoperationsconsoles/status
  - fabricoperatorapis/finalizers
  - fabricoperatorapis/status
  - fabricoperatoruis/finalizers
  - fabricoperatoruis/status
  - fabricorderernodes/finalizers
  - fabricorderernodes/status
  - fabricorderingservices/finalizers
  - fabricorderingservices/status
  - fabricpeers/finalizers
  - fabricpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
